### **Analisis Exploratorio de Datos con Python**

In [2]:
# importar la libreria Pandas 
import pandas as pd

In [ ]:
# Cargar el dataset a la libreta jupyter
df = pd.read_csv("./analisis_compras_clientes.csv")
df.iloc[::100].head(10) # Se utilizo iloc[::100] con el fin de poder ver diferentes partes del Dataset y no solo el inicio

,Cliente ID,Edad,Genero,Item Comprado,Categoria,Cantidad de Compra (USD),Ubicacion,Tamaño,Color,Temporada,Calificacion de Reviews,Status de Suscripcion,Tipo de Envio,Descuento Aplicado,Promocion Usada,Compras Anteriores,Metodo de Pago,Frecuencia de Compras
0,1,55,Masculino,Blusa,Vestimenta,53,Kentucky,L,Gris,Invierno,3.1,Si,Express,Si,Si,14,Venmo,Quincena
100,101,62,Masculino,Lentes de sol,Accesorios,98,South Dakota,M,Maroon,Otoño,2.7,Si,Express,Si,Si,31,Efectivo,Quincena
200,201,25,Masculino,Vestido,Vestimenta,61,Pennsylvania,S,Teal,Verano,3.3,Si,Envio Dia Siguiente,Si,Si,29,Venmo,Mensualmente
300,301,29,Masculino,Sombrero,Accesorios,98,Iowa,M,Teal,Primavera,4.4,Si,Recojer en Tienda,Si,Si,24,PayPal,Semanalmente
400,401,39,Masculino,Botas,Calzado,66,Utah,M,Verde,Invierno,4.8,Si,Envio Gratis,Si,Si,14,PayPal,Quincena
500,501,36,Masculino,Playera,Vestimenta,31,Washington,L,Morado,Otoño,4.8,Si,Envio Dia Siguiente,Si,Si,35,Venmo,Cada 3 Meses
600,601,22,Masculino,Sombrero,Accesorios,63,South Carolina,M,Charcoal,Primavera,5.0,Si,Envio 2-Dias,Si,Si,25,Venmo,Mensualmente
700,701,57,Masculino,Pantalones,Vestimenta,79,Wisconsin,L,Olive,Invierno,4.1,Si,Standard,Si,Si,5,PayPal,Mensualmente
800,801,32,Masculino,Calcetines,Vestimenta,20,Utah,S,Dorado,Verano,2.6,Si,Envio Gratis,Si,Si,20,Efectivo,Cada 3 Meses
900,901,54,Masculino,Sombrero,Accesorios,98,West Virginia,L,Gris,Otoño,3.3,Si,Envio Gratis,Si,Si,42,Transferencia Bancaria,Trimestral

In [5]:
# Usar df.info para revisar por encima la estructura del dataset 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Cliente ID                3900 non-null   int64
 1   Edad                      3900 non-null   int64
 2   Genero                    3900 non-null   object
 3   Item Comprado             3900 non-null   object
 4   Categoria                 3900 non-null   object
 5   Cantidad de Compra (USD)  3900 non-null   int64
 6   Ubicacion                 3900 non-null   object
 7   Tamaño                    3900 non-null   object
 8   Color                     3900 non-null   object
 9   Temporada                 3900 non-null   object
 10  Calificacion de Reviews   3863 non-null   float64
 11  Status de Suscripcion     3900 non-null   object
 12  Tipo de Envio             3900 non-null   object
 13  Descuento Aplicado        3900 non-null   object
 14  Promocion Usada           3900 non-null   object
 15  Compras Anteriores        3900 non-null   int64
 16  Metodo de Pago            3900 non-null   object
 17  Frecuencia de Compras     3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [6]:
# Resumen estadistico de todas las columnas usando .describe() 
df.describe(include='all')

,Cliente ID,Edad,Genero,Item Comprado,Categoria,Cantidad de Compra (USD),Ubicacion,Tamaño,Color,Temporada,Calificacion de Reviews,Status de Suscripcion,Tipo de Envio,Descuento Aplicado,Promocion Usada,Compras Anteriores,Metodo de Pago,Frecuencia de Compras
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Masculino,Blusa,Vestimenta,NaN,Montana,M,Olive,Primavera,NaN,No,Envio Gratis,No,No,NaN,PayPal,Cada 3 Meses
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [7]:
# Revisar las columnas donde hay 'null' en el dataset 
df.isnull().sum()

Cliente ID                   0
Edad                         0
Genero                       0
Item Comprado                0
Categoria                    0
Cantidad de Compra (USD)     0
Ubicacion                    0
Tamaño                       0
Color                        0
Temporada                    0
Calificacion de Reviews     37
Status de Suscripcion        0
Tipo de Envio                0
Descuento Aplicado           0
Promocion Usada              0
Compras Anteriores           0
Metodo de Pago               0
Frecuencia de Compras        0
dtype: int64

In [8]:
""" 
Agrupar las Reviews por Categoria:
- De esta manera se podra calcular facilmente la Mediana de las Reviews de acuerdo a su Categoria
- Una vez con la Mediana de las Categorias, remplazarlos por los valores que faltan a traves de 
la funcion lambda. 
"""

df['Calificacion de Reviews'] = df.groupby('Categoria')['Calificacion de Reviews'].transform(
    lambda x: x.fillna(x.median())
)

In [10]:
df.isnull().sum()

Cliente ID                  0
Edad                        0
Genero                      0
Item Comprado               0
Categoria                   0
Cantidad de Compra (USD)    0
Ubicacion                   0
Tamaño                      0
Color                       0
Temporada                   0
Calificacion de Reviews     0
Status de Suscripcion       0
Tipo de Envio               0
Descuento Aplicado          0
Promocion Usada             0
Compras Anteriores          0
Metodo de Pago              0
Frecuencia de Compras       0
dtype: int64

In [12]:
# Hacer todo minuscula y en vez de espacios utilizar guiones bajo 
# Tambien conocido como: Snake Case
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df.columns

Index(['cliente_id', 'edad', 'genero', 'item_comprado', 'categoria',
       'cantidad_de_compra_(usd)', 'ubicacion', 'tamaño', 'color', 'temporada',
       'calificacion_de_reviews', 'status_de_suscripcion', 'tipo_de_envio',
       'descuento_aplicado_', 'promocion_usada', 'compras_anteriores',
       'metodo_de_pago', 'frecuencia_de_compras'],
      dtype='object')

In [14]:
# Quitar (usd) en Cantidad de Compra y errores de espacio de las columnas
df = df.rename(columns={'cantidad_de_compra_(usd)':'cantidad_de_compra'})
df = df.rename(columns={'descuento_aplicado_':'descuento_aplicado'})
df.columns

Index(['cliente_id', 'edad', 'genero', 'item_comprado', 'categoria',
       'cantidad_de_compra', 'ubicacion', 'tamaño', 'color', 'temporada',
       'calificacion_de_reviews', 'status_de_suscripcion', 'tipo_de_envio',
       'descuento_aplicado', 'promocion_usada', 'compras_anteriores',
       'metodo_de_pago', 'frecuencia_de_compras'],
      dtype='object')

In [ ]:
# Crear nueva columna 'edad_grupo' con los siguientes labels
labels = ['Joven', 'Adulto', 'Mediana Edad', 'Anciano(a)']
# Segmentar la columna en 4 partes iguales y asignar los labels a traves de pd.qcut 
df['edad_grupo'] = pd.qcut(df['edad'], q=4, labels=labels)

In [18]:
# Revisar la agrupacion de acuerdo a los labels
df[['edad_grupo', 'edad']].iloc[::20].head(10)

       edad_grupo  edad
0    Mediana Edad    55
20          Joven    21
40     Anciano(a)    69
60   Mediana Edad    50
80          Joven    19
100    Anciano(a)    62
120    Anciano(a)    64
140    Anciano(a)    63
160         Joven    27
180  Mediana Edad    51

In [20]:
# Nueva Columna para asignar los dias de la frecuencia de las compras
# a traves de la funcion .map de pandas
mapeo_frecuencia = {
    'Quincena': 15,  
    'Semanalmente': 7,
    'Mensualmente': 30,
    'Trimestral': 90,
    'Cada 2 semanas': 14,
    'Anualmente': 365,
    'Cada 3 Meses': 90

}


df['dias_frecuencias_compras'] = df['frecuencia_de_compras'].map(mapeo_frecuencia)

In [22]:
# Revisar que se hayan asiganado a sus respectivos grupos
df[['frecuencia_de_compras', 'dias_frecuencias_compras']].head(10)

  frecuencia_de_compras  dias_frecuencias_compras
0              Quincena                        15
1              Quincena                        15
2          Semanalmente                         7
3          Semanalmente                         7
4            Anualmente                       365
5          Semanalmente                         7
6            Trimestral                        90
7          Semanalmente                         7
8            Anualmente                       365
9            Trimestral                        90

In [23]:
df['dias_frecuencias_compras'].unique()

array([ 15,   7, 365,  90,  14,  30], dtype=int64)

In [24]:
df['dias_frecuencias_compras'].dtype

dtype('int64')

In [36]:
df.columns

Index(['cliente_id', 'edad', 'genero', 'item_comprado', 'categoria',
       'cantidad_de_compra', 'ubicacion', 'tamaño', 'color', 'temporada',
       'calificacion_de_reviews', 'status_de_suscripcion', 'tipo_de_envio',
       'descuento_aplicado', 'compras_anteriores', 'metodo_de_pago',
       'frecuencia_de_compras', 'edad_grupo', 'dias_frecuencias_compras'],
      dtype='object')

In [ ]:
# Necesitamos ambas columnas? Ambas columnas tienen los mismos valores?
df[['descuento_aplicado','promocion_usada']].iloc[::700].head(5)

     descuento_aplicado promocion_usada
0                    Si              Si
700                  Si              Si
1400                 Si              Si
2100                 No              No
2800                 No              No

In [29]:
# Revisar si hay diferencias entre las columnas
(df['descuento_aplicado'] == df['promocion_usada']).all()

True

In [ ]:
# Ya que es verdadero se removera la columna de promocion_usada
df = df.drop('promocion_usada', axis=1) # Remover la columna (1 = columna, 0 = fila)
df.columns # Revisar que se quito

In [37]:
# Revisar el dataset modificado, cada 10 valores
df.iloc[::10]

,cliente_id,edad,genero,item_comprado,categoria,cantidad_de_compra,ubicacion,tamaño,color,temporada,calificacion_de_reviews,status_de_suscripcion,tipo_de_envio,descuento_aplicado,compras_anteriores,metodo_de_pago,frecuencia_de_compras,edad_grupo,dias_frecuencias_compras
0,1,55,Masculino,Blusa,Vestimenta,53,Kentucky,L,Gris,Invierno,3.1,Si,Express,Si,14,Venmo,Quincena,Mediana Edad,15
10,11,53,Masculino,Zapatos,Calzado,34,Arkansas,L,Morado,Otoño,4.1,Si,Recojer en Tienda,Si,26,Transferencia Bancaria,Cada 2 semanas,Mediana Edad,14
20,21,21,Masculino,Pantalones,Vestimenta,51,Louisiana,M,Negro,Invierno,2.8,Si,Express,Si,50,Efectivo,Cada 3 Meses,Joven,90
30,31,57,Masculino,Joyeria,Accesorios,31,North Carolina,L,Negro,Invierno,4.7,Si,Standard,Si,16,Tarjeta de Credito,Mensualmente,Mediana Edad,30
40,41,69,Masculino,Bolsa,Accesorios,76,Louisiana,L,Beige,Invierno,4.6,Si,Envio Dia Siguiente,Si,31,Tarjeta de Debito,Trimestral,Anciano(a),90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3850,3851,27,Femenino,Joyeria,Accesorios,74,Mississippi,L,Indigo,Verano,4.4,No,Envio 2-Dias,No,25,Tarjeta de Debito,Cada 3 Meses,Joven,90
3860,3861,57,Femenino,Lentes de sol,Accesorios,64,Pennsylvania,M,Turquesa,Verano,4.4,No,Envio Dia Siguiente,No,44,Efectivo,Anualmente,Mediana Edad,365
3870,3871,61,Femenino,Sandalias,Calzado,46,Ohio,L,Lavender,Otoño,3.2,No,Envio Dia Siguiente,No,19,Efectivo,Cada 3 Meses,Anciano(a),90
3880,3881,42,Femenino,Camiseta,Vestimenta,20,Massachusetts,M,Rojo,Invierno,3.9,No,Envio Gratis,No,40,PayPal,Mensualmente,Adulto,30
3890,3891,35,Femenino,Camiseta,Vestimenta,81,Nebraska,XL,Verde,Invierno,2.6,No,Standard,No,33,Tarjeta de Debito,Anualmente,Adulto,365

In [ ]:
# Guardar el dataset modificado en un XLSX 
df.to_excel('analisis_clientes_modificado.xlsx', index=False)

#### Conectar a MySQL

In [ ]:
# sqalchemy sirve como un puente entre python y bases de datos, en este caso MySQL
from sqlalchemy import create_engine

In [ ]:
# Instalar para crear la conexion entre Python y SQL
!pip install pymysql

Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2

In [ ]:
# Datos para la conexion a MySQL (Usar datos propios)
username = "****"
password = "*********" 
host = "localhost"
port = "****"
database = "proyecto_analisis_compras" 

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

# Escribir el DataFrame a MySQL
table_name = "clientes"  
df.to_sql(table_name, engine, if_exists="replace", index=False)

# Leer una muestra del dataset a traves de un comando de SQL
pd.read_sql("SELECT * FROM clientes LIMIT 10;", engine)

,cliente_id,edad,genero,item_comprado,categoria,cantidad_de_compra,ubicacion,tamaño,color,temporada,calificacion_de_reviews,status_de_suscripcion,tipo_de_envio,descuento_aplicado,compras_anteriores,metodo_de_pago,frecuencia_de_compras,edad_grupo,dias_frecuencias_compras
0,1,55,Masculino,Blusa,Vestimenta,53,Kentucky,L,Gris,Invierno,3.1,Si,Express,Si,14,Venmo,Quincena,Mediana Edad,15
1,2,19,Masculino,Sueter,Vestimenta,64,Maine,L,Maroon,Invierno,3.1,Si,Express,Si,2,Efectivo,Quincena,Joven,15
2,3,50,Masculino,Jeans,Vestimenta,73,Massachusetts,S,Maroon,Primavera,3.1,Si,Envio Gratis,Si,23,Tarjeta de Credito,Semanalmente,Mediana Edad,7
3,4,21,Masculino,Sandalias,Calzado,90,Rhode Island,M,Maroon,Primavera,3.5,Si,Envio Dia Siguiente,Si,49,PayPal,Semanalmente,Joven,7
4,5,45,Masculino,Blusa,Vestimenta,49,Oregon,M,Turquesa,Primavera,2.7,Si,Envio Gratis,Si,31,PayPal,Anualmente,Mediana Edad,365
5,6,46,Masculino,Tennis,Calzado,20,Wyoming,M,Blanco,Verano,2.9,Si,Standard,Si,14,Venmo,Semanalmente,Mediana Edad,7
6,7,63,Masculino,Camiseta,Vestimenta,85,Montana,M,Gris,Otoño,3.2,Si,Envio Gratis,Si,49,Efectivo,Trimestral,Anciano(a),90
7,8,27,Masculino,Shorts,Vestimenta,34,Louisiana,L,Charcoal,Invierno,3.2,Si,Envio Gratis,Si,19,Tarjeta de Credito,Semanalmente,Joven,7
8,9,26,Masculino,Abrigo,Ropa exterior,97,West Virginia,L,Plateado,Verano,2.6,Si,Express,Si,8,Venmo,Anualmente,Joven,365
9,10,57,Masculino,Bolsa,Accesorios,31,Missouri,M,Rosa,Primavera,4.8,Si,Envio 2-Dias,Si,4,Efectivo,Trimestral,Mediana Edad,90